source 'http://rubygems.org'
#:gemcutter

gem "sinatra"
gem "foreman"
gem "koala"
gem "json"
gem "httparty"
gem "thin"
gem "jsmin"
gem "cssmin"
gem "data_mapper"
gem "data_objects"
gem "dm-aggregates"
gem "dm-constraints"
gem "dm-core"
gem "dm-do-adapter"
gem "dm-migrations"
gem "dm-serializer"
#gem "dm-sqlite-adapter"
gem "dm-postgres-adapter"
gem "dm-timestamps"
gem "dm-transactions"
gem "dm-types"
gem "dm-validations"
gem "certified"
